
package de.pfnrw.jvault.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalBlockSizeException", targetNamespace = "http://server.jvault.pfnrw.de/")
public class IllegalBlockSizeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalBlockSizeException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IllegalBlockSizeException_Exception(String message, IllegalBlockSizeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IllegalBlockSizeException_Exception(String message, IllegalBlockSizeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.pfnrw.jvault.client.IllegalBlockSizeException
     */
    public IllegalBlockSizeException getFaultInfo() {
        return faultInfo;
    }

}
