
package de.pfnrw.jvault.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JSONException", targetNamespace = "http://server.jvault.pfnrw.de/")
public class JSONException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JSONException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public JSONException_Exception(String message, JSONException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public JSONException_Exception(String message, JSONException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.pfnrw.jvault.client.JSONException
     */
    public JSONException getFaultInfo() {
        return faultInfo;
    }

}
