
package de.pfnrw.jvault.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchPaddingException", targetNamespace = "http://server.jvault.pfnrw.de/")
public class NoSuchPaddingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchPaddingException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoSuchPaddingException_Exception(String message, NoSuchPaddingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoSuchPaddingException_Exception(String message, NoSuchPaddingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.pfnrw.jvault.client.NoSuchPaddingException
     */
    public NoSuchPaddingException getFaultInfo() {
        return faultInfo;
    }

}
