
package de.pfnrw.jvault.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VaultService", targetNamespace = "http://server.jvault.pfnrw.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VaultService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://server.jvault.pfnrw.de/", className = "de.pfnrw.jvault.client.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://server.jvault.pfnrw.de/", className = "de.pfnrw.jvault.client.SearchResponse")
    @Action(input = "http://server.jvault.pfnrw.de/VaultService/searchRequest", output = "http://server.jvault.pfnrw.de/VaultService/searchResponse")
    public String search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IllegalBlockSizeException_Exception
     * @throws InvalidKeySpecException_Exception
     * @throws NoSuchAlgorithmException_Exception
     * @throws JSONException_Exception
     * @throws BadPaddingException_Exception
     * @throws IOException_Exception
     * @throws InvalidKeyException_Exception
     * @throws NoSuchPaddingException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEntry", targetNamespace = "http://server.jvault.pfnrw.de/", className = "de.pfnrw.jvault.client.AddEntry")
    @ResponseWrapper(localName = "addEntryResponse", targetNamespace = "http://server.jvault.pfnrw.de/", className = "de.pfnrw.jvault.client.AddEntryResponse")
    @Action(input = "http://server.jvault.pfnrw.de/VaultService/addEntryRequest", output = "http://server.jvault.pfnrw.de/VaultService/addEntryResponse", fault = {
        @FaultAction(className = IllegalBlockSizeException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/IllegalBlockSizeException"),
        @FaultAction(className = IOException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/IOException"),
        @FaultAction(className = InvalidKeyException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/InvalidKeyException"),
        @FaultAction(className = InvalidKeySpecException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/InvalidKeySpecException"),
        @FaultAction(className = NoSuchAlgorithmException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/NoSuchAlgorithmException"),
        @FaultAction(className = NoSuchPaddingException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/NoSuchPaddingException"),
        @FaultAction(className = JSONException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/JSONException"),
        @FaultAction(className = BadPaddingException_Exception.class, value = "http://server.jvault.pfnrw.de/VaultService/addEntry/Fault/BadPaddingException")
    })
    public boolean addEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        Entry arg0)
        throws BadPaddingException_Exception, IOException_Exception, IllegalBlockSizeException_Exception, InvalidKeyException_Exception, InvalidKeySpecException_Exception, JSONException_Exception, NoSuchAlgorithmException_Exception, NoSuchPaddingException_Exception
    ;

}
