
package de.pfnrw.jvault.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VaultServiceService", targetNamespace = "http://server.jvault.pfnrw.de/", wsdlLocation = "http://localhost:9000/VaultService?wsdl")
public class VaultServiceService
    extends Service
{

    private final static URL VAULTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VAULTSERVICESERVICE_EXCEPTION;
    private final static QName VAULTSERVICESERVICE_QNAME = new QName("http://server.jvault.pfnrw.de/", "VaultServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/VaultService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VAULTSERVICESERVICE_WSDL_LOCATION = url;
        VAULTSERVICESERVICE_EXCEPTION = e;
    }

    public VaultServiceService() {
        super(__getWsdlLocation(), VAULTSERVICESERVICE_QNAME);
    }

    public VaultServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VAULTSERVICESERVICE_QNAME, features);
    }

    public VaultServiceService(URL wsdlLocation) {
        super(wsdlLocation, VAULTSERVICESERVICE_QNAME);
    }

    public VaultServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VAULTSERVICESERVICE_QNAME, features);
    }

    public VaultServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VaultServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VaultService
     */
    @WebEndpoint(name = "VaultServicePort")
    public VaultService getVaultServicePort() {
        return super.getPort(new QName("http://server.jvault.pfnrw.de/", "VaultServicePort"), VaultService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VaultService
     */
    @WebEndpoint(name = "VaultServicePort")
    public VaultService getVaultServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.jvault.pfnrw.de/", "VaultServicePort"), VaultService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VAULTSERVICESERVICE_EXCEPTION!= null) {
            throw VAULTSERVICESERVICE_EXCEPTION;
        }
        return VAULTSERVICESERVICE_WSDL_LOCATION;
    }

}
